---
- name: install python packages
  apt:
    pkg: 
    - python3
    - python3-pip
    state: present

- name: install pip packages
  pip:
    executable: pip3
    name: 
    - flask
    state: present

- name: Transfer app.py
  copy:
    src: app.py
    dest: /home/pi
    owner: pi
    group: pi
    mode: 0755
  register: apppy

- name: Transfer init.sh
  copy:
    src: init.sh
    dest: /home/pi
    owner: pi
    group: pi
    mode: 0755
  register: initsh

- name: Run Flask
  shell: /home/pi/init.sh