---
- name: Install packages
  action: >
    {{ ansible_pkg_mgr }} name={{ item }} state=present update_cache=yes
  with_items:
    - php
    - apache2
    - python

- name: Copy index.php
  copy: 
    src: index.php
    dest: /var/www/html/index.php
    owner: pi
    group: pi
    mode: 0644

- name: Copy display.py
  copy: 
    src: display.py
    dest: /var/www/html/display.py
    owner: pi
    group: pi
    mode: 0644

- name: Schedule display.py
  cron:
    name: "Display on sensehat"
    minute: "*"
    job: "python /var/www/html/display.py"