---
- name: Install packages
  apt: 
    name:
    - php
    - apache2
    - python
    - python-pip
    - sense-hat
    - vim
    state: present
    update_cache: yes

- name: Get I2C Setting
  shell: "raspi-config nonint get_i2c 0"
  register: I2C
  changed_when: I2C == 1

# https://github.com/mohankumargupta/raspberrypi-ansible/blob/master/raspbian-setup.yml
- name: Enable I2C
  shell: "raspi-config nonint do_i2c 0"
  when: I2C == 1

- name: Reboot
  reboot:
  when: I2C == 1

- name: Copy index.php
  copy: 
    src: index.php
    dest: /var/www/html/index.php
    owner: www-data
    group: www-data
    mode: 0644

- name: Copy display.py
  copy: 
    src: display.py
    dest: /var/www/html/display.py
    owner: www-data
    group: www-data
    mode: 0644

- name: Remove index.html
  file:
    state: absent
    path: /var/www/html/index.html

- name: Change permissions
  file:
    path: /var/www/html
    owner: www-data
    group: www-data

- name: Schedule display.py
  cron:
    name: "Display on sensehat"
    minute: "*"
    job: "python /var/www/html/display.py"